const DeliveryStatus = {
  RINGDOWN_SENT: 'RINGDOWN SENT',
  RINGDOWN_RECEIVED: 'RINGDOWN RECEIVED',
  ARRIVED: 'ARRIVED',
  OFFLOADED: 'OFFLOADED',
  RETURNED_TO_SERVICE: 'RETURNED TO SERVICE',
  CANCELLED: 'CANCELLED',
  CANCEL_ACKNOWLEDGED: 'CANCEL ACKNOWLEGED',
  REDIRECTED: 'REDIRECTED',
  REDIRECT_ACKNOWLEDGED: 'REDIRECT ACKNOWLEGED',
};

DeliveryStatus.ALL_STATUSES = [
  DeliveryStatus.RINGDOWN_SENT,
  DeliveryStatus.RINGDOWN_RECEIVED,
  DeliveryStatus.ARRIVED,
  DeliveryStatus.OFFLOADED,
  DeliveryStatus.RETURNED_TO_SERVICE,
  DeliveryStatus.CANCELLED,
  DeliveryStatus.CANCEL_ACKNOWLEDGED,
  DeliveryStatus.REDIRECTED,
  DeliveryStatus.REDIRECT_ACKNOWLEDGED,
];

Object.freeze(DeliveryStatus);

module.exports = DeliveryStatus;
