services:
  db:
    image: postgres:12
  server:
    build: .
    command: bash -l -c "yarn && yarn start:prod"
    env_file:
      - .env
    ports:
      - ${HOST_PORT:-3000}:3000
    depends_on:
      - db
  mail:
    image: dockage/mailcatcher:0.8.2
    ports:
      - 1025:1025
      - 1080:1080
